[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info

[program:ss-manager]
command=ss-manager
    --manager-address 127.0.0.1:%(ENV_SS_MANAGER_PORT)s
    --executable /usr/bin/ss-server
    -m %(ENV_SS_METHOD)s
    -u
priority=10
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/ss-manager.stdout.log
stderr_logfile=/var/log/supervisor/ss-manager.stderr.log

[program:web]
command=/opt/venv/bin/python /app/app.py
priority=20
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/web.stdout.log
stderr_logfile=/var/log/supervisor/web.stderr.log
environment=SS_MANAGER_PORT="%(ENV_SS_MANAGER_PORT)s",WEB_PORT="%(ENV_WEB_PORT)s",SS_METHOD="%(ENV_SS_METHOD)s"
